fix: update fonts generation steps

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -160,6 +160,57 @@ cmn::step::start "Generating Files"
 LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${build_dir}/server/FileConverter/bin"
 export LD_LIBRARY_PATH
 
+#cmn::task::start "Generating Fonts"
+
+#if ! "${build_dir}/server/tools/allfontsgen" \
+#		--input="${build_dir}/core-fonts" \
+#		--allfonts-web="${build_dir}/sdkjs/common/AllFonts.js" \
+#		--allfonts="${build_dir}/server/FileConverter/bin/AllFonts.js" \
+#		--images="${build_dir}/sdkjs/common/Images" \
+#		--selection="${build_dir}/server/FileConverter/bin/font_selection.bin" \
+#		--output-web="${build_dir}/fonts" \
+#		--use-system="true"
+#then
+#	cmn::task::fail
+#	cmn::step::fail
+#	exit 20
+#fi
+
+#cmn::task::finish
+
+#cmn::task::start "Generating Themes"
+
+#if ! "${build_dir}/server/tools/allthemesgen" \
+#		--src="${build_dir}/sdkjs/slide/themes"\
+#		--converter-dir="${build_dir}/server/FileConverter/bin"\
+#		--output="${build_dir}/sdkjs/common/Images"
+#then
+#	cmn::task::fail
+#	cmn::step::fail
+#	exit 21
+#fi
+
+#cmn::task::finish
+
+
+cmn::task::start "Updating Fonts Paths"
+
+# Font paths are generated during build, so that all paths are prefixed with
+# `/build/<UUID>`.
+# At runtime, this path doesn't exist and must be replaced with `/app`:
+
+font_files=(
+	${HOME}/server/FileConverter/bin/AllFonts.js
+	${HOME}/server/FileConverter/bin/font_selection.bin
+	${HOME}/sdkjs/common/AllFonts.js
+)
+
+for f in "${font_files[@]}"; do
+	sed -i -E 's/\/build\/[a-z0-9-]{36}/\/app/g' "${f}"
+done
+
+cmn::task::finish
+
 cmn::task::start "Generating Fonts"
 
 if ! "${build_dir}/server/tools/allfontsgen" \
@@ -193,23 +244,6 @@ fi
 cmn::task::finish
 
 
-cmn::task::start "Updating Fonts Paths"
-
-# Font paths are generated during build, so that all paths are prefixed with
-# `/build/<UUID>`.
-# At runtime, this path doesn't exist and must be replaced with `/app`:
-
-font_files=(
-	${HOME}/server/FileConverter/bin/AllFonts.js
-	${HOME}/server/FileConverter/bin/font_selection.bin
-	${HOME}/sdkjs/common/AllFonts.js
-)
-
-for f in "${font_files[@]}"; do
-	sed -i -E 's/\/build\/[a-z0-9-]{36}/\/app/g' "${f}"
-done
-
-#cmn::task::finish
 
 cmn::step::finish
 
